export const quotes: {quote: string, author: string}[] = [
  { "quote": "The purpose of our lives is to be happy.", "author": "Dalai Lama" },
  { "quote": "Life is what happens when you’re busy making other plans.", "author": "John Lennon" },
  { "quote": "Get busy living or get busy dying.", "author": "Stephen King" },
  { "quote": "You only live once, but if you do it right, once is enough.", "author": "Mae West" },
  { "quote": "Many of life’s failures are people who did not realize how close they were to success when they gave up.", "author": "Thomas A. Edison" },
  { "quote": "If you want to live a happy life, tie it to a goal, not to people or things.", "author": "Albert Einstein" },
  { "quote": "Never let the fear of striking out keep you from playing the game.", "author": "Babe Ruth" },
  { "quote": "Money and success don’t change people; they merely amplify what is already there.", "author": "Will Smith" },
  { "quote": "Your time is limited, so don’t waste it living someone else’s life. Don’t be trapped by dogma – which is living with the results of other people’s thinking.", "author": "Steve Jobs" },
  { "quote": "Not how long, but how well you have lived is the main thing.", "author": "Seneca" },
  { "quote": "If life were predictable it would cease to be life, and be without flavor.", "author": "Eleanor Roosevelt" },
  { "quote": "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.", "author": "Henry Ford" },
  { "quote": "In order to write about life first you must live it.", "author": "Ernest Hemingway" },
  { "quote": "The big lesson in life, baby, is never be scared of anyone or anything.", "author": "Frank Sinatra" },
  { "quote": "Sing like no one’s listening, love like you’ve never been hurt, dance like nobody’s watching, and live like it’s heaven on earth.", "author": "Attributed to various sources" },
  { "quote": "Curiosity about life in all of its aspects, I think, is still the secret of great creative people.", "author": "Leo Burnett" },
  { "quote": "Life is not a problem to be solved, but a reality to be experienced.", "author": "Soren Kierkegaard" },
  { "quote": "The unexamined life is not worth living.", "author": "Socrates" },
  { "quote": "Turn your wounds into wisdom.", "author": "Oprah Winfrey" },
  { "quote": "The way I see it, if you want the rainbow, you gotta put up with the rain.", "author": "Dolly Parton" },
  { "quote": "Do all the good you can, for all the people you can, in all the ways you can, as long as you can.", "author": "Hillary Clinton (inspired by John Wesley quote)" },
  { "quote": "Don’t settle for what life gives you; make life better and build something.", "author": "Ashton Kutcher" },
  {
    "quote": "Everybody wants to be famous, but nobody wants to do the work. I live by that. You grind hard so you can play hard. At the end of the day, you put all the work in, and eventually it’ll pay off. It could be in a year, it could be in 30 years.Eventually, your hard work will pay off.",
    "author": "Kevin Hart"
  },
  { "quote": "Everything negative – pressure, challenges – is all an opportunity for me to rise.", "author": "Kobe Bryant" },
  { "quote": "I like criticism. It makes you strong.", "author": "LeBron James" },
  { "quote": "You never really learn much from hearing yourself speak.", "author": "George Clooney" },
  { "quote": "Life imposes things on you that you can’t control, but you still have the choice of how you’re going to live through this.", "author": "Celine Dion" },
  { "quote": "Life is never easy. There is work to be done and obligations to be met – obligations to truth, to justice, and to liberty.", "author": "John F. Kennedy" },
  { "quote": "Live for each second without hesitation.", "author": "Elton John" },
  { "quote": "Life is like riding a bicycle. To keep your balance, you must keep moving.", "author": "Albert Einstein" }];
